### PR TITLE
Scala 2.13

### PR DESCRIPTION
**Pull request by ignacioPL**
I upgrade all dependencies to Scala 2.13 and change the alpakka test for the new akka-stream-alpakka-s3 version.

### CODE REVIEW

**Comment by lorenzhawkes** [comment]
Looks like the travis ci version has changed so oraclejdk8 is nolonger supported. https://travis-ci.community/t/install-of-oracle-jdk8-is-failing/4365

**Comment by chvitved** [comment]
So happy you are putting effort into this @ignacioPL. 
Would love to see a release supporting scala 2.13. I had to build a local s3-mock jar from your branch to move forward with upgrading our project.

**Comment by jrouly** [comment]
@shuttie any chance of this getting merged?

**Comment by jrouly** [comment]
I've pushed up https://github.com/ignacioPL/s3mock/pull/1 against this PR to:
* add scala 2.13 to the readme,
* actually add it to `ThisBuild` so that it gets picked up

`sbt +compile +test:compile +test` works locally for me with that PR.

**Comment by anilkumarmyla** [comment]
Looking for this change, any chance someone made a fork and published it for scala 2.13?

**Comment by cvdsteeg** [comment]
I'd love to see this merged as well, any progress yet?

**Comment by jrouly** [comment]
I contacted `findify` by email and they indicated it was on their radar at least, but couldn't commit to a time to merge it. Not sure how actively this repo is being maintained by them.

**Comment by anilkumarmyla** [comment]
🥳

**Pull request merged**
